device: cuda:0
input_image_size: 96
loss:
    params: {}
    type: crossentropy
multispecter_bands_indices:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
path_to_dataset_root: C:\Users\mokhail\develop\DATA\DATA_FOR_TRAINIG_96
segmentation_nn:
    input_layer_params:
        layer_path: encoder._conv_stem
        layers_num: 1
        padding: !!python/tuple
        - 1
        - 1
        stride: !!python/tuple
        - 2
        - 2
    nn_architecture: unet++
    params:
        activation: null
        aux_params: null
        classes: 11
        decoder_attention_type: null
        decoder_channels: !!python/tuple
        - 256
        - 128
        - 64
        - 32
        - 16
        decoder_interpolation: nearest
        decoder_use_norm: batchnorm
        encoder_depth: 5
        encoder_name: efficientnet-b0
        encoder_weights: imagenet
        in_channels: 3
