batch_size: 16
device: cuda:0
epoch_num: 300
input_image_size: 96
loss:
    params:
        ignore_index: -100
        label_smoothing: 0.15
        reduction: mean
        weight: null
    type: crossentropy
lr_scheduler:
    args:
        T_0: 25
        T_mult: 1
        eta_min: 0
        last_epoch: -1
    params:
        frequency: 1
        interval: epoch
        monitor: val_loss
        name: null
        strict: true
    type: cosine_warm_restarts
multispecter_bands_indices:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
name_postfix: null
optimizer:
    args: {}
    type: adam
#path_to_dataset_root: C:\Users\admin\python_programming\DATA\DATA_FOR_TRAINIG_96
path_to_dataset_root: C:\Users\mokhail\develop\DATA\DATA_FOR_TRAINIG_96
#path_to_dataset_root: /home/mikhail_u/develop/DATA/DATA_FOR_TRAINIG_96
segmentation_nn:
    input_layer_config:
        layer_path: encoder._conv_stem
        params:
            aggregation_type: add
            bias:
                1x1: false
                3x3: false
            dilation:
                1x1: 1
                3x3: 1
            groups:
                1x1: 1
                3x3: 1
            in_channels: 3
            kernel_size:
                1x1: 1
                3x3: 3
            out_channels:
                1x1: 32
                3x3: 32
            padding:
                1x1: 0
                3x3: 1
            stride:
                1x1: 1
                3x3: 1
        replace_type: multisize_conv
        weight_update_type: repeat
    nn_architecture: custom_fpn
    params:
        activation: null
        aux_params: null
        classes: 11
        decoder_dropout: 0.2
        decoder_interpolation: nearest
        decoder_merge_policy: add
        decoder_pyramid_channels: 128
        decoder_segmentation_channels: 128
        encoder_depth: 5
        encoder_name: efficientnet-b0
        encoder_weights: imagenet
        in_channels: 3
        upsampling: 0
train_augmentations:
    affine:
        degrees:
        - 0
        - 45
        fill:
        - 0
        scale:
        - 0.7
        - 1.5
        shear:
        - 0
        - 0.2
        translate:
        - 0
        - 0.3
    gauss_noise:
        clip: false
        mean: 0.0
        sigma: 0.0008
    horizontal_flip:
        p: 0.5
    perspective:
        distortion_scale: 0.2
        fill:
        - 0
        p: 0.3
    vertical_flip:
        p: 0.5
